app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, lm
from flask.ext.login import UserMixin


class Usuario(UserMixin, db.Model):
    __tablename__ = "usuarios"
    id = db.Column(db.Integer, primary_key=True)
    nombre = db.Column(db.String(16), index=True, unique=True)
    password_hash = db.Column(db.String(64))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    @staticmethod
    def registra(usuario, password):
        user = Usuario(nombre=usuario)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return user

    def __repr__(self):
        return "{}".format(self.nombre)

@lm.user_loader
def load_user(id):
    return Usuario.query.get(int(id))

app/main/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Length


class LoginForm(Form):
    usuario = StringField("Usuario:", validators=[Required(), Length(1, 16)])
    password = PasswordField('Contraseña', validators=[Required()])
    recordarme = BooleanField("Recordarme")
    submit = SubmitField("Entrar")

app/__init__.py
import os
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager


bootstrap = Bootstrap()
db = SQLAlchemy()
lm = LoginManager()
lm.login_view = 'main.login'


def create_app(config_name):
    app = Flask(__name__)

    cfg = os.path.join(os.getcwd(), 'config', config_name + '.py')
    app.config.from_pyfile(cfg)

    bootstrap.init_app(app)
    db.init_app(app)
    lm.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes

app/main/routes.py
from flask import render_template, redirect, url_for, request
from flask.ext.login import login_user, logout_user, login_required
from ..models import Usuario
from . import main
from .forms import LoginForm


@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        usr = Usuario.query.filter_by(nombre=form.usuario.data).first()
        if usr is None or not usr.verify_password(form.password.data):
            return redirect(url_for('main.login', **request.args))
        login_user(usr, form.password.data)
        return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('login.html', form=form)

@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/protected')
@login_required
def protected():
    return render_template('protected.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Ejemplo de Login{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('main.index') }}">
                Ejemplo de Login
            </a>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Inicio</a></li>
                <li><a href="{{ url_for('main.protected') }}">Área Protegida</a></li>
            </ul>>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {% if current_user.is_authenticated() %}
                        <a href="{{ url_for('main.logout') }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('main.login') }}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %}Ejemplo de Login{% endblock %}

{% block page_content %}
    <h1>Principal</h1>
    <p>Esto puede ser visto por cualquier usuario (logeado o público)</p>
    <p>Estás {% if not current_user.is_authenticated() %}no {% endif %}logueado.</p>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Ejemplo de Login{% endblock %}

{% block page_content %}
    <h1>Login</h1>
    <div class="row">
        <div class="col-md-3">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
{% endblock %}

app/templates/protected.html
{% extends "base.html" %}

{% block title %}Ejemplo de Login{% endblock %}

{% block page_content %}
    <h1>Área protegida</h1>
    <p>solo visible por usuarios "logeados"</p>
    <p>logeaste como: <b>{{ current_user.nombre }}</b>.</p>
{% endblock %}

templates/base.html
{% extends "bootstrap/base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Ejemplo de Login{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('index') }}">
                Ejemplo de Login
            </a>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('index') }}">Inicio</a></li>
                <li><a href="{{ url_for('protected') }}">Área Protegida</a></li>
            </ul>>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    {% if current_user.is_authenticated() %}
                        <a href="{{ url_for('logout') }}">Logout</a>
                    {% else %}
                        <a href="{{ url_for('login') }}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}